import { Suggestion } from './suggestion.model';

/** Demo data until the backend delivers real suggestions. */
export const MOCK_SUGGESTIONS: Suggestion[] = [
  {
    id: 'c1',
    kind: 'mail',
    kindLabel: 'E-Mail',
    title: 'Lena eine kurze Follow-up-Mail zum Angebot schreiben',
    contact: { name: 'Lena Hoffmann', role: 'Head of Operations', company: 'Nordwerk Logistik', initials: 'LH', avatarColor: '#CDBEF7' },
    dealValue: '48.000 €',
    stage: 'Verhandlung',
    lastContact: 'vor 9 Tagen',
    confidence: 91,
    bestTime: 'Heute, 10:00 Uhr',
    draftLabel: 'E-Mail-Entwurf',
    subject: 'Betreff: Kurz die Laufzeit klären?',
    draft:
      'Hallo Lena,\n\nich habe gesehen, dass ihr euch unser Angebot diese Woche noch einmal angeschaut habt. Sollen wir die offene Frage zur Vertragslaufzeit am Dienstag in 20 Minuten klären?\n\nIch hätte 10:00 oder 14:30 Uhr frei.\n\nBeste Grüße\nMarco',
    summary:
      'Lena ist aktiv interessiert, aber seit dem letzten Call blockiert eine einzige offene Frage. Ein kurzer, konkreter Terminvorschlag löst das am wahrscheinlichsten.',
    evidence: [
      { source: 'E-Mail-Tracking', text: 'Angebot seit Montag 3× geöffnet, zuletzt heute um 08:12 Uhr', weight: 92 },
      { source: 'Call-Notiz · 11. Sep', text: 'Vertragslaufzeit als einziger offener Punkt genannt', weight: 81 },
      { source: 'Postfach', text: '9 Tage ohne Antwort – sonst antwortet sie im Schnitt nach 2 Tagen', weight: 70 },
      { source: 'Muster', text: 'Antwortet am häufigsten Di–Do zwischen 9 und 11 Uhr', weight: 46 },
    ],
    onApprove: 'Bei Freigabe geht die Mail um 10:00 Uhr aus deinem Postfach raus und wird am Deal protokolliert.',
    scheduledLabel: 'Mail an Lena geplant',
    scheduledTime: '10:00 Uhr',
  },
  {
    id: 'c2',
    kind: 'call',
    kindLabel: 'Anruf',
    title: 'Tobias anrufen, bevor der Vertrag ausläuft',
    contact: { name: 'Tobias Brandt', role: 'CFO', company: 'Kessler & Söhne', initials: 'TB', avatarColor: '#F6C9A8' },
    dealValue: '126.000 €',
    stage: 'Verlängerung',
    lastContact: 'vor 5 Wochen',
    confidence: 78,
    bestTime: 'Heute, 15:30 Uhr',
    draftLabel: 'Gesprächsleitfaden',
    draft:
      '1. Danke für drei Jahre Zusammenarbeit – kurz auf die Erfolge im Einkauf verweisen.\n\n2. Nachfragen, wie der neue Standort in Leipzig anläuft und wer dort das Team führt.\n\n3. Rückgang der Nutzung offen ansprechen: Gibt es etwas, das fehlt?\n\n4. Ziel: Termin für das Verlängerungsgespräch vor dem 15. Oktober fixieren.',
    summary:
      'Der Vertrag läuft in drei Wochen aus und die Nutzung sinkt. Bei diesem Muster rettet ein persönlicher Anruf deutlich öfter die Verlängerung als eine Mail.',
    evidence: [
      { source: 'Vertrag', text: 'Laufzeit endet am 15. Oktober – noch 21 Tage', weight: 94 },
      { source: 'Produktnutzung', text: 'Aktive Nutzer im Team seit sechs Wochen um 18 % gesunken', weight: 83 },
      { source: 'News', text: 'Pressemeldung: Kessler & Söhne eröffnet einen Standort in Leipzig', weight: 61 },
      { source: 'Deine Historie', text: 'Deine letzten zwei Verlängerungen mit Nutzungsrückgang hast du per Telefon gewonnen', weight: 55 },
    ],
    onApprove: 'Bei Freigabe blockt Cherrypick 15:30 Uhr in deinem Kalender und legt den Leitfaden in die Anrufnotiz.',
    scheduledLabel: 'Anruf mit Tobias eingeplant',
    scheduledTime: '15:30 Uhr',
  },
  {
    id: 'c3',
    kind: 'offer',
    kindLabel: 'Angebot',
    title: 'Aylin das Upgrade auf „Team Pro“ anbieten',
    contact: { name: 'Aylin Demir', role: 'Gründerin', company: 'Studio Parallax', initials: 'AD', avatarColor: '#BFE3D0' },
    dealValue: '14.400 € / Jahr',
    stage: 'Bestandskunde',
    lastContact: 'vor 2 Tagen',
    confidence: 84,
    bestTime: 'Morgen, 09:00 Uhr',
    draftLabel: 'E-Mail mit Angebot',
    subject: 'Betreff: Mehr Platz für euer Team',
    draft:
      'Hallo Aylin,\n\neuer Team ist gewachsen – ihr nutzt inzwischen 4 von 5 Plätzen. Mit „Team Pro“ bekommt ihr unbegrenzte Plätze und genau die Freigabe-Workflows, nach denen du im Support gefragt hast.\n\nIch habe dir ein Angebot angehängt, gültig bis Ende Oktober.\n\nViele Grüße\nMarco',
    summary:
      'Studio Parallax stößt an die Grenze des aktuellen Plans und hat selbst nach einer Pro-Funktion gefragt. Das Timing für ein Upgrade ist ideal.',
    evidence: [
      { source: 'Lizenzen', text: '4 von 5 Plätzen belegt, zwei neue Einladungen ausstehend', weight: 88 },
      { source: 'Support-Ticket', text: 'Frage nach Freigabe-Workflows – nur in „Team Pro“ enthalten', weight: 86 },
      { source: 'Vergleichbare Kunden', text: 'Kunden mit diesem Muster haben in 2 von 3 Fällen innerhalb von 30 Tagen upgegradet', weight: 58 },
    ],
    onApprove: 'Bei Freigabe erstellt Cherrypick das Angebot als PDF, hängt es an und sendet morgen um 09:00 Uhr.',
    scheduledLabel: 'Angebot an Aylin geplant',
    scheduledTime: 'morgen 09:00',
  },
  {
    id: 'c4',
    kind: 'meeting',
    kindLabel: 'Termin',
    title: 'Jonas eine Live-Demo für nächste Woche vorschlagen',
    contact: { name: 'Jonas Weber', role: 'CTO', company: 'Flux Robotics', initials: 'JW', avatarColor: '#A9D4F5' },
    dealValue: '62.000 €',
    stage: 'Qualifizierung',
    lastContact: 'vor 3 Tagen',
    confidence: 73,
    bestTime: 'Heute, 11:30 Uhr',
    draftLabel: 'Termineinladung',
    subject: 'Betreff: 30 Minuten Demo – API & Integrationen',
    draft:
      'Hallo Jonas,\n\ndanke für deine Fragen zur API. Am schnellsten lässt sich das live zeigen – ich schlage eine 30-minütige Demo vor, gern zusammen mit eurem Lead Developer.\n\nVorschläge: Mi, 30.09. um 10:00 Uhr oder Do, 01.10. um 16:00 Uhr.\n\nViele Grüße\nMarco',
    summary:
      'Jonas prüft gerade technisch, ob ihr zusammenpasst. Eine Live-Demo mit seinem Entwickler bringt den Deal aus der Evaluierung in die nächste Phase.',
    evidence: [
      { source: 'Website', text: 'API-Dokumentation 5× besucht, zweimal gemeinsam mit einem Kollegen', weight: 84 },
      { source: 'E-Mail', text: 'Hat drei technische Fragen zu Webhooks gestellt', weight: 77 },
      { source: 'Kalender', text: 'Du hast Mittwoch und Donnerstag noch passende Slots frei', weight: 40 },
    ],
    onApprove:
      'Bei Freigabe verschickt Cherrypick die Einladung mit zwei Terminvorschlägen und reserviert beide vorläufig in deinem Kalender.',
    scheduledLabel: 'Einladung an Jonas geplant',
    scheduledTime: '11:30 Uhr',
  },
  {
    id: 'c5',
    kind: 'mail',
    kindLabel: 'E-Mail',
    title: 'Sarah zum Abschluss gratulieren und das Onboarding anstoßen',
    contact: { name: 'Sarah Klein', role: 'Leitung Einkauf', company: 'Brightline Medical', initials: 'SK', avatarColor: '#F3D98B' },
    dealValue: '89.000 €',
    stage: 'Gewonnen',
    lastContact: 'gestern',
    confidence: 95,
    bestTime: 'Jetzt',
    draftLabel: 'E-Mail-Entwurf',
    subject: 'Betreff: Willkommen an Bord!',
    draft:
      'Hallo Sarah,\n\nvielen Dank für euer Vertrauen – wir freuen uns sehr auf die Zusammenarbeit!\n\nDamit euer Team schnell startklar ist, würde ich gern ein Kick-off mit unserer Onboarding-Managerin Julia vereinbaren. Passt dir kommende Woche?\n\nHerzliche Grüße\nMarco',
    summary:
      'Der Vertrag wurde gestern unterschrieben. Wer in den ersten 48 Stunden ein Kick-off terminiert, startet schneller und bleibt länger Kunde.',
    evidence: [
      { source: 'E-Signatur', text: 'Vertrag gestern um 17:40 Uhr unterschrieben', weight: 96 },
      { source: 'Onboarding', text: 'Noch kein Kick-off-Termin angelegt', weight: 80 },
      { source: 'Muster', text: 'Kunden mit Kick-off innerhalb von 2 Tagen sind im Schnitt 3 Wochen früher produktiv', weight: 62 },
    ],
    onApprove: 'Bei Freigabe geht die Mail sofort raus, Julia wird in Kopie gesetzt.',
    scheduledLabel: 'Mail an Sarah gesendet',
    scheduledTime: 'jetzt',
  },
  {
    id: 'c6',
    kind: 'call',
    kindLabel: 'Anruf',
    title: 'Mehmet nach vier Monaten Funkstille wieder anrufen',
    contact: { name: 'Mehmet Yılmaz', role: 'Geschäftsführer', company: 'Yılmaz Bau', initials: 'MY', avatarColor: '#E9B8C9' },
    dealValue: '35.000 €',
    stage: 'Pausiert',
    lastContact: 'vor 4 Monaten',
    confidence: 66,
    bestTime: 'Morgen, 08:00 Uhr',
    draftLabel: 'Gesprächsleitfaden',
    draft:
      '1. Kurz anknüpfen: Im Mai habt ihr das Projekt wegen der Bausaison verschoben.\n\n2. Nachfragen, ob die Planung für das Frühjahr schon läuft.\n\n3. Das neue Modul für Baustellen-Dokumentation erwähnen – das hatte er sich damals gewünscht.\n\n4. Ziel: Okay, ein aktualisiertes Angebot zu schicken.',
    summary:
      'Mehmet hat das Projekt damals nur aufgeschoben, nicht abgesagt. Die Bausaison endet, und die Funktion, die ihm gefehlt hat, gibt es jetzt.',
    evidence: [
      { source: 'CRM-Notiz · Mai', text: '„Nach der Saison gern wieder melden“', weight: 82 },
      { source: 'Produkt-Update', text: 'Modul Baustellen-Dokumentation ist seit August verfügbar', weight: 74 },
      { source: 'Muster', text: 'Meist früh morgens vor 8:30 Uhr erreichbar', weight: 44 },
    ],
    onApprove: 'Bei Freigabe legt Cherrypick den Anruf für morgen 08:00 Uhr in deinen Kalender.',
    scheduledLabel: 'Anruf mit Mehmet eingeplant',
    scheduledTime: 'morgen 08:00',
  },
  {
    id: 'c7',
    kind: 'offer',
    kindLabel: 'Angebot',
    title: 'Clara das Angebot für den zweiten Standort schicken',
    contact: { name: 'Clara Neumann', role: 'Operations Managerin', company: 'Hafenküche Gruppe', initials: 'CN', avatarColor: '#D6CDB8' },
    dealValue: '22.800 €',
    stage: 'Expansion',
    lastContact: 'vor 6 Tagen',
    confidence: 81,
    bestTime: 'Heute, 14:00 Uhr',
    draftLabel: 'E-Mail mit Angebot',
    subject: 'Betreff: Angebot für den Standort Altona',
    draft:
      'Hallo Clara,\n\nwie besprochen schicke ich dir das Angebot für euren neuen Standort in Altona. Ich habe die Konditionen eures ersten Standorts übernommen und die Einrichtung kostenfrei eingerechnet.\n\nMeld dich gern, wenn du Fragen hast.\n\nBeste Grüße\nMarco',
    summary:
      'Clara hat im letzten Gespräch um ein Angebot gebeten, das noch nicht verschickt wurde. Jeder weitere Tag Verzögerung kostet Abschlusschance.',
    evidence: [
      { source: 'Call-Notiz · 18. Sep', text: 'Clara hat ausdrücklich um ein Angebot bis Ende der Woche gebeten', weight: 93 },
      { source: 'CRM', text: 'Aufgabe „Angebot erstellen“ ist seit 6 Tagen offen', weight: 78 },
      { source: 'Bestandskunde', text: 'Der erste Standort nutzt das Produkt täglich, ohne Support-Tickets', weight: 57 },
    ],
    onApprove: 'Bei Freigabe erstellt Cherrypick das Angebot als PDF und sendet es heute um 14:00 Uhr.',
    scheduledLabel: 'Angebot an Clara geplant',
    scheduledTime: '14:00 Uhr',
  },
];
